-- BCP 47 language tags with English display names (reference)
create table if not exists public.bcp47_language_tags (
  tag text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.bcp47_language_tags is 'BCP 47 / Unicode locale identifiers with English labels';

alter table public.bcp47_language_tags enable row level security;

insert into public.bcp47_language_tags (tag, name) values
  ('ak-GH', 'Akan (Ghana)'),
  ('ar-DZ', 'Arabic (Algeria)'),
  ('sq', 'Albanian'),
  ('sq-AL', 'Albanian (Albania)'),
  ('ar-BH', 'Arabic (Bahrain)'),
  ('ak', 'Akan'),
  ('ar', 'Arabic'),
  ('ar-TD', 'Arabic (Chad)'),
  ('sq-MK', 'Albanian (Macedonia)'),
  ('sq-XK', 'Albanian (Kosovo)'),
  ('af-ZA', 'Afrikaans (South Africa)'),
  ('af', 'Afrikaans'),
  ('am', 'Amharic'),
  ('am-ET', 'Amharic (Ethiopia)'),
  ('af-NA', 'Afrikaans (Namibia)'),
  ('ar-DJ', 'Arabic (Djibouti)'),
  ('ar-IQ', 'Arabic (Iraq)'),
  ('ar-LB', 'Arabic (Lebanon)'),
  ('ar-SO', 'Arabic (Somalia)'),
  ('ar-SS', 'Arabic (South Sudan)'),
  ('ar-SA', 'Arabic (Saudi Arabia)'),
  ('ar-OM', 'Arabic (Oman)'),
  ('ar-PS', 'Arabic (Palestinian Territories)'),
  ('ar-MA', 'Arabic (Morocco)'),
  ('ar-MR', 'Arabic (Mauritania)'),
  ('ar-IL', 'Arabic (Israel)'),
  ('ar-ER', 'Arabic (Eritrea)'),
  ('ar-KM', 'Arabic (Comoros)'),
  ('ar-KW', 'Arabic (Kuwait)'),
  ('ar-EG', 'Arabic (Egypt)'),
  ('ar-JO', 'Arabic (Jordan)'),
  ('ar-LY', 'Arabic (Libya)'),
  ('ar-QA', 'Arabic (Qatar)'),
  ('az-AZ', 'Azerbaijani (Azerbaijan)'),
  ('ar-SD', 'Arabic (Sudan)'),
  ('eu-ES', 'Basque (Spain)'),
  ('hy-AM', 'Armenian (Armenia)'),
  ('hy', 'Armenian'),
  ('kw', 'Cornish'),
  ('en-PR', 'English (Puerto Rico)'),
  ('en-SD', 'English (Sudan)'),
  ('ee-TG', 'Ewe (Togo)'),
  ('fr-MQ', 'French (Martinique)'),
  ('ff', 'Fulah'),
  ('gu', 'Gujarati'),
  ('he-IL', 'Hebrew (Israel)'),
  ('hi', 'Hindi'),
  ('ig', 'Igbo'),
  ('kk-Cyrl', 'Kazakh (Cyrillic)'),
  ('ko-KP', 'Korean (North Korea)'),
  ('lv', 'Latvian'),
  ('se-SE', 'Northern Sami (Sweden)'),
  ('nn', 'Norwegian Nynorsk'),
  ('fa-AF', 'Persian (Afghanistan)'),
  ('pt-ST', 'Portuguese (São Tomé & Príncipe)'),
  ('pa-IN', 'Punjabi (India)'),
  ('es-NI', 'Spanish (Nicaragua)'),
  ('sw-TZ', 'Swahili (Tanzania)'),
  ('ti-ER', 'Tigrinya (Eritrea)'),
  ('ug-CN', 'Uyghur (China)'),
  ('bn-IN', 'Bengali (India)'),
  ('bg', 'Bulgarian'),
  ('zh-Hant', 'Chinese (Traditional)'),
  ('nl-AW', 'Dutch (Aruba)'),
  ('en-IM', 'English (Isle of Man)'),
  ('en-GB', 'English (United Kingdom)'),
  ('ee', 'Ewe'),
  ('ee-GH', 'Ewe (Ghana)'),
  ('fr-BJ', 'French (Benin)'),
  ('fr-BI', 'French (Burundi)'),
  ('fr-GA', 'French (Gabon)'),
  ('fr-YT', 'French (Mayotte)'),
  ('ff-MR', 'Fulah (Mauritania)'),
  ('de-LI', 'German (Liechtenstein)'),
  ('is-IS', 'Icelandic (Iceland)'),
  ('ig-NG', 'Igbo (Nigeria)'),
  ('ga', 'Irish'),
  ('ko-KR', 'Korean (South Korea)'),
  ('ky', 'Kyrgyz'),
  ('ln-CD', 'Lingala (Congo-Kinshasa)'),
  ('lt-LT', 'Lithuanian (Lithuania)'),
  ('mt', 'Maltese'),
  ('nn-NO', 'Norwegian Nynorsk (Norway)'),
  ('pt-TL', 'Portuguese (Timor-Leste)'),
  ('pa-Guru', 'Punjabi (Gurmukhi)'),
  ('sg', 'Sango'),
  ('gd', 'Scottish Gaelic'),
  ('sr-Cyrl', 'Serbian (Cyrillic)'),
  ('si', 'Sinhala'),
  ('so-KE', 'Somali (Kenya)'),
  ('so-SO', 'Somali (Somalia)'),
  ('es-GQ', 'Spanish (Equatorial Guinea)'),
  ('es-GT', 'Spanish (Guatemala)'),
  ('es-HN', 'Spanish (Honduras)'),
  ('sv-AX', 'Swedish (Åland Islands)'),
  ('tr', 'Turkish'),
  ('uz-UZ', 'Uzbek (Uzbekistan)'),
  ('vi-VN', 'Vietnamese (Vietnam)'),
  ('az-Latn', 'Azerbaijani (Latin)'),
  ('as', 'Assamese'),
  ('my', 'Burmese'),
  ('ca', 'Catalan'),
  ('da-DK', 'Danish (Denmark)'),
  ('nl-BE', 'Dutch (Belgium)'),
  ('en-IO', 'English (British Indian Ocean Territory)'),
  ('en-GM', 'English (Gambia)'),
  ('en-JE', 'English (Jersey)'),
  ('en-MW', 'English (Malawi)'),
  ('en-FM', 'English (Micronesia)'),
  ('en-PH', 'English (Philippines)'),
  ('en-SZ', 'English (Swaziland)'),
  ('fr-GF', 'French (French Guiana)'),
  ('fr-GP', 'French (Guadeloupe)'),
  ('fr-MA', 'French (Morocco)'),
  ('fr-RW', 'French (Rwanda)'),
  ('fr-VU', 'French (Vanuatu)'),
  ('ka', 'Georgian'),
  ('kl-GL', 'Kalaallisut (Greenland)'),
  ('ki-KE', 'Kikuyu (Kenya)'),
  ('mr', 'Marathi'),
  ('mr-IN', 'Marathi (India)'),
  ('ne-IN', 'Nepali (India)'),
  ('os-GE', 'Ossetic (Georgia)'),
  ('ro-RO', 'Romanian (Romania)'),
  ('es-CU', 'Spanish (Cuba)'),
  ('ta-IN', 'Tamil (India)'),
  ('bo-CN', 'Tibetan (China)'),
  ('bo-IN', 'Tibetan (India)'),
  ('ti-ET', 'Tigrinya (Ethiopia)'),
  ('ur-IN', 'Urdu (India)'),
  ('ug', 'Uyghur'),
  ('yo-NG', 'Yoruba (Nigeria)'),
  ('zu-ZA', 'Zulu (South Africa)'),
  ('en-GD', 'English (Grenada)'),
  ('en-MO', 'English (Macau SAR China)'),
  ('en-MH', 'English (Marshall Islands)'),
  ('en-NA', 'English (Namibia)'),
  ('en-NG', 'English (Nigeria)'),
  ('en-PK', 'English (Pakistan)'),
  ('en-RW', 'English (Rwanda)'),
  ('en-SH', 'English (St. Helena)'),
  ('en-US', 'English (United States)'),
  ('fr-MR', 'French (Mauritania)'),
  ('fr-BL', 'French (St. Barthélemy)'),
  ('fr-TN', 'French (Tunisia)'),
  ('hi-IN', 'Hindi (India)'),
  ('is', 'Icelandic'),
  ('or-IN', 'Oriya (India)'),
  ('pt-CV', 'Portuguese (Cape Verde)'),
  ('qu-PE', 'Quechua (Peru)'),
  ('sr-ME', 'Serbian (Montenegro)'),
  ('sn-ZW', 'Shona (Zimbabwe)'),
  ('sl-SI', 'Slovenian (Slovenia)'),
  ('es-EA', 'Spanish (Ceuta & Melilla)'),
  ('es-CO', 'Spanish (Colombia)'),
  ('es-PR', 'Spanish (Puerto Rico)'),
  ('ta-SG', 'Tamil (Singapore)'),
  ('te', 'Telugu'),
  ('cy-GB', 'Welsh (United Kingdom)'),
  ('bs', 'Bosnian'),
  ('nl', 'Dutch'),
  ('dz-BT', 'Dzongkha (Bhutan)'),
  ('en-AI', 'English (Anguilla)'),
  ('en-ER', 'English (Eritrea)'),
  ('en-MY', 'English (Malaysia)'),
  ('en-SG', 'English (Singapore)'),
  ('fo-FO', 'Faroese (Faroe Islands)'),
  ('fi', 'Finnish'),
  ('fr-CA', 'French (Canada)'),
  ('fr-KM', 'French (Comoros)'),
  ('fr-NC', 'French (New Caledonia)'),
  ('fr-NE', 'French (Niger)'),
  ('fr-RE', 'French (Réunion)'),
  ('lg', 'Ganda'),
  ('de', 'German'),
  ('de-LU', 'German (Luxembourg)'),
  ('hu-HU', 'Hungarian (Hungary)'),
  ('it', 'Italian'),
  ('ja', 'Japanese'),
  ('kl', 'Kalaallisut'),
  ('lt', 'Lithuanian'),
  ('ms', 'Malay'),
  ('gv-IM', 'Manx (Isle of Man)'),
  ('nd', 'North Ndebele'),
  ('se-NO', 'Northern Sami (Norway)'),
  ('os-RU', 'Ossetic (Russia)'),
  ('pt-AO', 'Portuguese (Angola)'),
  ('pa-Arab', 'Punjabi (Arabic)'),
  ('ug-Arab', 'Uyghur (Arabic)'),
  ('uz-AF', 'Uzbek (Afghanistan)'),
  ('cy', 'Welsh'),
  ('bs-Cyrl', 'Bosnian (Cyrillic)'),
  ('en', 'English'),
  ('en-KY', 'English (Cayman Islands)'),
  ('en-CC', 'English (Cocos (Keeling) Islands)'),
  ('en-CK', 'English (Cook Islands)'),
  ('en-DG', 'English (Diego Garcia)'),
  ('en-MT', 'English (Malta)'),
  ('en-NR', 'English (Nauru)'),
  ('en-SC', 'English (Seychelles)'),
  ('en-SS', 'English (South Sudan)'),
  ('en-ZM', 'English (Zambia)'),
  ('fo', 'Faroese'),
  ('fr-CD', 'French (Congo-Kinshasa)'),
  ('fr-ML', 'French (Mali)'),
  ('it-CH', 'Italian (Switzerland)'),
  ('lv-LV', 'Latvian (Latvia)'),
  ('lb-LU', 'Luxembourgish (Luxembourg)'),
  ('se-FI', 'Northern Sami (Finland)'),
  ('or', 'Oriya'),
  ('ro', 'Romanian'),
  ('sr-RS', 'Serbian (Serbia)'),
  ('so-DJ', 'Somali (Djibouti)'),
  ('sw', 'Swahili'),
  ('sv-SE', 'Swedish (Sweden)'),
  ('vi', 'Vietnamese'),
  ('nl-CW', 'Dutch (Curaçao)'),
  ('nl-NL', 'Dutch (Netherlands)'),
  ('en-AS', 'English (American Samoa)'),
  ('en-GU', 'English (Guam)'),
  ('en-KE', 'English (Kenya)'),
  ('en-TK', 'English (Tokelau)'),
  ('fr-FR', 'French (France)'),
  ('fr-PF', 'French (French Polynesia)'),
  ('fr-MC', 'French (Monaco)'),
  ('he', 'Hebrew'),
  ('it-SM', 'Italian (San Marino)'),
  ('ja-JP', 'Japanese (Japan)'),
  ('lo-LA', 'Lao (Laos)'),
  ('ln-CG', 'Lingala (Congo-Brazzaville)'),
  ('ml', 'Malayalam'),
  ('ps', 'Pashto'),
  ('pt-BR', 'Portuguese (Brazil)'),
  ('pt-GW', 'Portuguese (Guinea-Bissau)'),
  ('ru-BY', 'Russian (Belarus)'),
  ('ru-MD', 'Russian (Moldova)'),
  ('ru-UA', 'Russian (Ukraine)'),
  ('sr-BA', 'Serbian (Bosnia & Herzegovina)'),
  ('sr-Latn', 'Serbian (Latin)'),
  ('sn', 'Shona'),
  ('es-AR', 'Spanish (Argentina)'),
  ('es-PE', 'Spanish (Peru)'),
  ('ta-MY', 'Tamil (Malaysia)'),
  ('bo', 'Tibetan'),
  ('to', 'Tongan'),
  ('tr-TR', 'Turkish (Turkey)'),
  ('yo-BJ', 'Yoruba (Benin)'),
  ('bn', 'Bengali'),
  ('ar-EH', 'Arabic (Western Sahara)'),
  ('ca-AD', 'Catalan (Andorra)'),
  ('ca-FR', 'Catalan (France)'),
  ('ca-ES', 'Catalan (Spain)'),
  ('zh-SG', 'Chinese (Singapore)'),
  ('en-AG', 'English (Antigua & Barbuda)'),
  ('en-BB', 'English (Barbados)'),
  ('en-VG', 'English (British Virgin Islands)'),
  ('en-CX', 'English (Christmas Island)'),
  ('en-DM', 'English (Dominica)'),
  ('en-GH', 'English (Ghana)'),
  ('en-HK', 'English (Hong Kong SAR China)'),
  ('en-MG', 'English (Madagascar)'),
  ('en-PG', 'English (Papua New Guinea)'),
  ('en-TT', 'English (Trinidad & Tobago)'),
  ('en-TC', 'English (Turks & Caicos Islands)'),
  ('fi-FI', 'Finnish (Finland)'),
  ('fr-CG', 'French (Congo-Brazzaville)'),
  ('fr-CI', 'French (Côte d''Ivoire)'),
  ('fr-MU', 'French (Mauritius)'),
  ('fr-SY', 'French (Syria)'),
  ('ff-SN', 'Fulah (Senegal)'),
  ('ha-NG', 'Hausa (Nigeria)'),
  ('it-IT', 'Italian (Italy)'),
  ('lo', 'Lao'),
  ('ln-AO', 'Lingala (Angola)'),
  ('mg', 'Malagasy'),
  ('ms-SG', 'Malay (Singapore)'),
  ('om-ET', 'Oromo (Ethiopia)'),
  ('os', 'Ossetic'),
  ('qu-BO', 'Quechua (Bolivia)'),
  ('ro-MD', 'Romanian (Moldova)'),
  ('rn', 'Rundi'),
  ('es-CL', 'Spanish (Chile)'),
  ('tl-PH', 'Tagalog (Philippines)'),
  ('tr-CY', 'Turkish (Cyprus)'),
  ('uk', 'Ukrainian'),
  ('ur', 'Urdu'),
  ('uz-Cyrl', 'Uzbek (Cyrillic)'),
  ('uz-Latn', 'Uzbek (Latin)'),
  ('eu', 'Basque'),
  ('be-BY', 'Belarusian (Belarus)'),
  ('br-FR', 'Breton (France)'),
  ('da-GL', 'Danish (Greenland)'),
  ('en-GI', 'English (Gibraltar)'),
  ('eo', 'Esperanto'),
  ('et-EE', 'Estonian (Estonia)'),
  ('fr-SC', 'French (Seychelles)'),
  ('ka-GE', 'Georgian (Georgia)'),
  ('gu-IN', 'Gujarati (India)'),
  ('ha', 'Hausa'),
  ('rw', 'Kinyarwanda'),
  ('ln', 'Lingala'),
  ('ms-Latn', 'Malay (Latin)'),
  ('ms-MY', 'Malay (Malaysia)'),
  ('mn', 'Mongolian'),
  ('sh-BA', 'Serbo-Croatian (Bosnia & Herzegovina)'),
  ('ii-CN', 'Sichuan Yi (China)'),
  ('so', 'Somali'),
  ('es-CR', 'Spanish (Costa Rica)'),
  ('es-PH', 'Spanish (Philippines)'),
  ('es-VE', 'Spanish (Venezuela)'),
  ('sw-UG', 'Swahili (Uganda)'),
  ('tl', 'Tagalog'),
  ('te-IN', 'Telugu (India)'),
  ('fy', 'Western Frisian'),
  ('yi', 'Yiddish'),
  ('zu', 'Zulu'),
  ('ar-SY', 'Arabic (Syria)'),
  ('bm', 'Bambara'),
  ('ar-TN', 'Arabic (Tunisia)'),
  ('bm-Latn', 'Bambara (Latin)'),
  ('my-MM', 'Burmese (Myanmar (Burma))'),
  ('zh-HK', 'Chinese (Hong Kong SAR China)'),
  ('zh-Hans', 'Chinese (Simplified)'),
  ('hr-BA', 'Croatian (Bosnia & Herzegovina)'),
  ('hr-HR', 'Croatian (Croatia)'),
  ('en-BE', 'English (Belgium)'),
  ('en-BM', 'English (Bermuda)'),
  ('en-CM', 'English (Cameroon)'),
  ('ar-YE', 'Arabic (Yemen)'),
  ('en-KI', 'English (Kiribati)'),
  ('en-SB', 'English (Solomon Islands)'),
  ('en-VC', 'English (St. Vincent & Grenadines)'),
  ('en-TO', 'English (Tonga)'),
  ('fr-HT', 'French (Haiti)'),
  ('fr-CH', 'French (Switzerland)'),
  ('gl-ES', 'Galician (Spain)'),
  ('kn-IN', 'Kannada (India)'),
  ('ki', 'Kikuyu'),
  ('ky-KG', 'Kyrgyz (Kyrgyzstan)'),
  ('gv', 'Manx'),
  ('pl-PL', 'Polish (Poland)'),
  ('pt', 'Portuguese'),
  ('pa', 'Punjabi'),
  ('qu', 'Quechua'),
  ('es-SV', 'Spanish (El Salvador)'),
  ('th', 'Thai'),
  ('th-TH', 'Thai (Thailand)'),
  ('az-Cyrl', 'Azerbaijani (Cyrillic)'),
  ('zh', 'Chinese'),
  ('zh-CN', 'Chinese (China)'),
  ('kw-GB', 'Cornish (United Kingdom)'),
  ('cs', 'Czech'),
  ('en-CA', 'English (Canada)'),
  ('en-FJ', 'English (Fiji)'),
  ('en-GG', 'English (Guernsey)'),
  ('en-JM', 'English (Jamaica)'),
  ('en-LS', 'English (Lesotho)'),
  ('en-MU', 'English (Mauritius)'),
  ('en-NZ', 'English (New Zealand)'),
  ('en-MP', 'English (Northern Mariana Islands)'),
  ('en-ZA', 'English (South Africa)'),
  ('en-TZ', 'English (Tanzania)'),
  ('en-TV', 'English (Tuvalu)'),
  ('fr-CM', 'French (Cameroon)'),
  ('fr-LU', 'French (Luxembourg)'),
  ('ff-GN', 'Fulah (Guinea)'),
  ('lg-UG', 'Ganda (Uganda)'),
  ('de-AT', 'German (Austria)'),
  ('hu', 'Hungarian'),
  ('ga-IE', 'Irish (Ireland)'),
  ('ks', 'Kashmiri'),
  ('km-KH', 'Khmer (Cambodia)'),
  ('rw-RW', 'Kinyarwanda (Rwanda)'),
  ('ne-NP', 'Nepali (Nepal)'),
  ('no-NO', 'Norwegian (Norway)'),
  ('nb-SJ', 'Norwegian Bokmål (Svalbard & Jan Mayen)'),
  ('om', 'Oromo'),
  ('om-KE', 'Oromo (Kenya)'),
  ('pt-MZ', 'Portuguese (Mozambique)'),
  ('gd-GB', 'Scottish Gaelic (United Kingdom)'),
  ('sh', 'Serbo-Croatian'),
  ('sk', 'Slovak'),
  ('so-ET', 'Somali (Ethiopia)'),
  ('es', 'Spanish'),
  ('es-DO', 'Spanish (Dominican Republic)'),
  ('es-EC', 'Spanish (Ecuador)'),
  ('es-US', 'Spanish (United States)'),
  ('ta-LK', 'Tamil (Sri Lanka)'),
  ('to-TO', 'Tongan (Tonga)'),
  ('uk-UA', 'Ukrainian (Ukraine)'),
  ('ur-PK', 'Urdu (Pakistan)'),
  ('ar-AE', 'Arabic (United Arab Emirates)'),
  ('dz', 'Dzongkha'),
  ('en-BZ', 'English (Belize)'),
  ('en-BW', 'English (Botswana)'),
  ('en-GY', 'English (Guyana)'),
  ('en-PW', 'English (Palau)'),
  ('en-SL', 'English (Sierra Leone)'),
  ('en-SX', 'English (Sint Maarten)'),
  ('en-UM', 'English (U.S. Outlying Islands)'),
  ('fr', 'French'),
  ('fr-PM', 'French (St. Pierre & Miquelon)'),
  ('fr-WF', 'French (Wallis & Futuna)'),
  ('ff-CM', 'Fulah (Cameroon)'),
  ('gl', 'Galician'),
  ('el-GR', 'Greek (Greece)'),
  ('kn', 'Kannada'),
  ('kk-KZ', 'Kazakh (Kazakhstan)'),
  ('lu-CD', 'Luba-Katanga (Congo-Kinshasa)'),
  ('mg-MG', 'Malagasy (Madagascar)'),
  ('ms-BN', 'Malay (Brunei)'),
  ('ml-IN', 'Malayalam (India)'),
  ('pl', 'Polish'),
  ('pt-PT', 'Portuguese (Portugal)'),
  ('pa-PK', 'Punjabi (Pakistan)'),
  ('rm', 'Romansh'),
  ('ru-KG', 'Russian (Kyrgyzstan)'),
  ('sr', 'Serbian'),
  ('sr-XK', 'Serbian (Kosovo)'),
  ('sk-SK', 'Slovak (Slovakia)'),
  ('es-IC', 'Spanish (Canary Islands)'),
  ('es-PA', 'Spanish (Panama)'),
  ('bs-BA', 'Bosnian (Bosnia & Herzegovina)'),
  ('bs-Latn', 'Bosnian (Latin)'),
  ('br', 'Breton'),
  ('hr', 'Croatian'),
  ('da', 'Danish'),
  ('nl-SR', 'Dutch (Suriname)'),
  ('en-LR', 'English (Liberia)'),
  ('en-PN', 'English (Pitcairn Islands)'),
  ('en-VI', 'English (U.S. Virgin Islands)'),
  ('en-ZW', 'English (Zimbabwe)'),
  ('fr-DZ', 'French (Algeria)'),
  ('fr-TD', 'French (Chad)'),
  ('fr-DJ', 'French (Djibouti)'),
  ('fr-MG', 'French (Madagascar)'),
  ('de-DE', 'German (Germany)'),
  ('ha-NE', 'Hausa (Niger)'),
  ('ks-Arab', 'Kashmiri (Arabic)'),
  ('mt-MT', 'Maltese (Malta)'),
  ('ne', 'Nepali'),
  ('se', 'Northern Sami'),
  ('ps-AF', 'Pashto (Afghanistan)'),
  ('pt-MO', 'Portuguese (Macau SAR China)'),
  ('rn-BI', 'Rundi (Burundi)'),
  ('ru', 'Russian'),
  ('sg-CF', 'Sango (Central African Republic)'),
  ('ti', 'Tigrinya'),
  ('fy-NL', 'Western Frisian (Netherlands)'),
  ('az', 'Azerbaijani'),
  ('be', 'Belarusian'),
  ('as-IN', 'Assamese (India)'),
  ('bn-BD', 'Bengali (Bangladesh)'),
  ('bg-BG', 'Bulgarian (Bulgaria)'),
  ('ca-IT', 'Catalan (Italy)'),
  ('nl-BQ', 'Dutch (Caribbean Netherlands)'),
  ('en-BS', 'English (Bahamas)'),
  ('en-FK', 'English (Falkland Islands)'),
  ('en-IE', 'English (Ireland)'),
  ('en-KN', 'English (St. Kitts & Nevis)'),
  ('fr-BE', 'French (Belgium)'),
  ('fr-CF', 'French (Central African Republic)'),
  ('fr-GQ', 'French (Equatorial Guinea)'),
  ('fr-SN', 'French (Senegal)'),
  ('fr-MF', 'French (St. Martin)'),
  ('fr-TG', 'French (Togo)'),
  ('de-BE', 'German (Belgium)'),
  ('id', 'Indonesian'),
  ('lu', 'Luba-Katanga'),
  ('lb', 'Luxembourgish'),
  ('mk', 'Macedonian'),
  ('mn-MN', 'Mongolian (Mongolia)'),
  ('nd-ZW', 'North Ndebele (Zimbabwe)'),
  ('fa', 'Persian'),
  ('rm-CH', 'Romansh (Switzerland)'),
  ('sl', 'Slovenian'),
  ('es-BO', 'Spanish (Bolivia)'),
  ('es-ES', 'Spanish (Spain)'),
  ('sw-KE', 'Swahili (Kenya)'),
  ('sv-FI', 'Swedish (Finland)'),
  ('ta', 'Tamil'),
  ('yo', 'Yoruba'),
  ('nl-SX', 'Dutch (Sint Maarten)'),
  ('et', 'Estonian'),
  ('de-CH', 'German (Switzerland)'),
  ('el-CY', 'Greek (Cyprus)'),
  ('ha-GH', 'Hausa (Ghana)'),
  ('ks-IN', 'Kashmiri (India)'),
  ('ko', 'Korean'),
  ('mk-MK', 'Macedonian (Macedonia)'),
  ('mn-Cyrl', 'Mongolian (Cyrillic)'),
  ('no', 'Norwegian'),
  ('nb', 'Norwegian Bokmål'),
  ('fa-IR', 'Persian (Iran)'),
  ('ru-RU', 'Russian (Russia)'),
  ('ii', 'Sichuan Yi'),
  ('es-MX', 'Spanish (Mexico)'),
  ('es-UY', 'Spanish (Uruguay)'),
  ('sv', 'Swedish'),
  ('uz', 'Uzbek'),
  ('uz-Arab', 'Uzbek (Arabic)'),
  ('zh-MO', 'Chinese (Macau SAR China)'),
  ('zh-TW', 'Chinese (Taiwan)'),
  ('cs-CZ', 'Czech (Czech Republic)'),
  ('en-AU', 'English (Australia)'),
  ('en-IN', 'English (India)'),
  ('en-MS', 'English (Montserrat)'),
  ('en-NU', 'English (Niue)'),
  ('en-NF', 'English (Norfolk Island)'),
  ('en-WS', 'English (Samoa)'),
  ('en-LC', 'English (St. Lucia)'),
  ('en-UG', 'English (Uganda)'),
  ('en-VU', 'English (Vanuatu)'),
  ('fr-BF', 'French (Burkina Faso)'),
  ('fr-GN', 'French (Guinea)'),
  ('el', 'Greek'),
  ('ha-Latn', 'Hausa (Latin)'),
  ('id-ID', 'Indonesian (Indonesia)'),
  ('kk', 'Kazakh'),
  ('km', 'Khmer'),
  ('ky-Cyrl', 'Kyrgyz (Cyrillic)'),
  ('ln-CF', 'Lingala (Central African Republic)'),
  ('nb-NO', 'Norwegian Bokmål (Norway)'),
  ('qu-EC', 'Quechua (Ecuador)'),
  ('ru-KZ', 'Russian (Kazakhstan)'),
  ('si-LK', 'Sinhala (Sri Lanka)'),
  ('es-PY', 'Spanish (Paraguay)')
on conflict (tag) do update set
  name = excluded.name,
  updated_at = now();
